site_name: Documentación de Alvaro
remote_branch: master
theme: readthedocs
pages:
- Home: index.md
- Trabajo:
  - Smart Cities: smart_cities.md
  - Universidad de Málaga: uma.md
  - FIWARE: fiware.md
  - Video: video.md
  - Espacios Digitales: espacios_digitales.md
- Personal:
  - Data Science:
    - General: data_science/general.md
    - Cursos: data_science/cursos.md
    - Python: data_science/python.md
    - R: data_science/R.md
  - Ssh: ssh.md
  - Vim: vim.md
  - Emmet: emmet.md
  - Git: git.md
  - Markdown: markdown.md
  - Homebrew: brew.md
  - Robocopy: robocopy.md
  - Lossless: lossless.md
