site_name: Documentaci√≥n de Alvaro
remote_branch: master
theme: mkdocs
pages:
- Home: index.md
- Trabajo:
  - Video: video.md
  - Espacios Digitales: espacios_digitales.md
- Personal:
  - Data Science:
    - R: data_science/R.md
    - Python: data_science/python.md
  - Ssh: ssh.md
  - Vim: vim.md
  - Git: git.md
  - Markdown: markdown.md
  - Homebrew: brew.md
  - Robocopy: robocopy.md
  - Lossless: lossless.md
